### ISSUE TITLE
Attention on the Profile Fragment Views

### ISSUE THREAD

**Issue by bagaspranawa** [C23-PS419/PetaniKita-MobileApp#18]
I have implemented local and network data persistence to accommodate the user data on the profile page. In order to showcase the result of this implementation, I need to add some TextViews to the UI. Please note that these changes may lead to merge conflicts, so please ensure that the existing TextViews in the profile UI are aligned with the ones I have created.

**Comment by risangbaskoro** [comment]
Which branch / PR are you referring that to?

**Comment by aleirsyad** [comment]
https://github.com/C23-PS419/PetaniKita-MobileApp/pull/19

**Comment by risangbaskoro** [comment]
Reopening this issue until #19 is closed.
